@startuml
!$_live_test = %false()
Class01 <|-- Class02
Class03 *-- Class04
!if $_live_test
Class05 o-- Class06
!if $_live_test
Class07 .. Class08
Class09 -- Class9
!endif /' _live_test '/
!endif


/' @plantuml-live-editor views v2
{
  "activeView": "Default",
  "views": {
    "Default": {
      "SOMETHING": true
    }
  }
}
@end-plantuml-live-editor views '/
@enduml